name: Trigger Notejoke Build

on:
  push:
    paths:
      - 'result.txt'
    branches: [ main ]

jobs:
  trigger-notejoke:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Notejoke build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.NOTEJOKE_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/yusdesign/notejoke/actions/workflows/android-build.yml/dispatches \
            -d '{"ref":"main"}'
